Feature/workout view
ThePhoneBeLinging/TrainingApp pull request #11
Opened 2024-10-28 21:29 UTC by Hartwich75

Jeg har lavet workoutView færdig, så den viser alle exercises i en givet workout. Der er i koden (under edit workout knappen) blevet lavet en testWorkout, dette var for at teste hvordan det så ud. Man kan nu også klikke på både billedet af en exercise eller exercise navnet, for at få exerciseDetailsViewet af den exercise der blev klikket på. Derudover har jeg også fået lavet exercises i workoutView scrollable, så man kan scroll igennem dem. Har også bare lige refactoret images i deres egen mappe under resources.

2024-10-28 22:01 UTC, ThePhoneBeLinging requested changes

2024-10-29 13:11 UTC, emilsavino requested changes

2024-10-29 13:11 UTC, emilsavino commented on src/main/java/Group15/ExerciseDetailsView.java
>          return new Scene(layout, 1000, 800);
You should not set the size of the scene

2024-10-29 13:11 UTC, emilsavino commented on src/main/java/Group15/WorkoutView.java
> +        return new Scene(layout, 1000, 800);
You should not set the size of the scene here either

2024-10-29 13:27 UTC, ThePhoneBeLinging approved these changes

2024-10-29 13:27 UTC, emilsavino approved these changes

2024-10-29 13:28 UTC, merged