Feature/skeleton homescreen
ThePhoneBeLinging/TrainingApp pull request #3
Opened 2024-10-12 09:48 UTC by emilsavino

2024-10-12 16:10 UTC, ThePhoneBeLinging requested changes

2024-10-12 16:10 UTC, ThePhoneBeLinging commented on src/main/java/Group15/HomeScreenView.java
> +    public static Scene getScene() {
Method name doesn't reflect what the function does right now

2024-10-12 16:10 UTC, ThePhoneBeLinging commented on src/main/java/Group15/HomeScreenView.java
> +    public static Scene getScene() {
Either change, or update so object caches a created scene

2024-10-12 16:23 UTC, ThePhoneBeLinging approved these changes

2024-10-19 09:36 UTC, FredBas approved these changes
looks good after method name has been changed

2024-10-19 11:15 UTC, merged