Feature/randomize button for muscle view
ThePhoneBeLinging/TrainingApp pull request #40
Opened 2024-11-22 15:55 UTC by WettyWednesday

2024-11-24 09:02 UTC, ThePhoneBeLinging approved these changes

2024-11-24 09:02 UTC, ThePhoneBeLinging commented on src/main/java/Group15/View/MuscleSelectionView.java
> +    private static final Map<BodyPart, Button> bodyPartButtonMap = new HashMap<>();
ArrayList would have been more efficient

2024-11-24 09:04 UTC, ThePhoneBeLinging requested changes
I am able to get 0 muscles selected

2024-11-24 09:56 UTC, emilsavino approved these changes

2024-11-24 09:57 UTC, emilsavino reviewed
wooops did not see mr mike found some issues

2024-11-25 08:12 UTC, Hartwich75 approved these changes

2024-11-25 10:00 UTC, ThePhoneBeLinging approved these changes

2024-11-25 10:00 UTC, merged