Should have a duration for the workoutView now
ThePhoneBeLinging/TrainingApp pull request #44
Opened 2024-11-23 18:23 UTC by WettyWednesday

2024-11-24 15:26 UTC, emilsavino requested changes
Also something seems to be wrong as i just got a crazy amount of of exercises for a 30 minute workout

2024-11-24 15:26 UTC, emilsavino commented on src/main/java/Group15/Model/Workout.java
> +    public static final int BREAK_BETWEEN_SETS = 180000;
isn't this quite a long break?

2024-11-24 15:26 UTC, emilsavino commented on src/main/java/Group15/Util/WorkoutAlgorithm.java
> +                int timeUsedThisSet = workout.getWorkoutDuration() + timePerSet;
This is does not appear to be the time used this set but time used in total up to that point.
Plus you are calling getWorkoutDuration a few times here, which is not very efficient as the method has to iterate through the whole workout every time.

2024-11-24 15:27 UTC, ThePhoneBeLinging commented on src/main/java/Group15/Model/Workout.java
> +    public static final int BREAK_BETWEEN_SETS = 180000;
Its in milliseconds :)

2024-11-24 15:28 UTC, emilsavino commented on src/main/java/Group15/Model/Workout.java
> +    public static final int BREAK_BETWEEN_SETS = 180000;
i know but its 3 minutes

2024-11-24 15:29 UTC, ThePhoneBeLinging commented on src/main/java/Group15/Model/Workout.java
> +    public static final int BREAK_BETWEEN_SETS = 180000;
Fred said 3 minutes

2024-11-25 09:35 UTC, ThePhoneBeLinging approved these changes

2024-11-25 09:39 UTC, emilsavino approved these changes

2024-11-25 09:44 UTC, merged