Feature/saved workouts list
ThePhoneBeLinging/TrainingApp pull request #48
Opened 2024-11-24 21:28 UTC by FredBas

homeview now shows a list of the actual saved workouts. Save button in workoutview has also been changed so a popup appears prompting user to choose between save locally and print to pdf
![image](https://github.com/user-attachments/assets/edb72883-0845-42cc-af8b-cd29e36fda38)

2024-11-24 21:45 UTC, WettyWednesday requested changes
For me it doesnt show the name of the workout on the homescreen. And one has to close the program, and open it again for the workout to be there. Seems a bit tedious. We should probably also remove descriptions for workouts as these cannot be inputted anywhere right now

2024-11-24 21:45 UTC, WettyWednesday commented on src/main/java/Group15/View/HomeScreenView.java
> +        } else {
The method for this should probably be a ScrollPane instead of Pane, as one cannot see all the exercises otherwise

2024-11-25 09:03 UTC, FredBas commented
Fixed everything. I will not fix the issue with descriptions as it is not a responsibility of this feature

2024-11-25 09:15 UTC, FredBas commented
![image](https://github.com/user-attachments/assets/0c447ab0-ae76-447a-a4af-3d4726281c5a)

2024-11-25 09:23 UTC, Hartwich75 approved these changes

2024-11-25 09:24 UTC, merged