Feature/popular workouts
ThePhoneBeLinging/TrainingApp pull request #55
Opened 2024-11-25 14:13 UTC by Hartwich75

I have created 4 popular workouts, which are displayed on the HomeScreenViews and can be loaded by clicking on them

2024-11-25 14:33 UTC, emilsavino approved these changes

2024-11-25 16:09 UTC, WettyWednesday requested changes

2024-11-25 16:09 UTC, WettyWednesday commented on src/main/resources/userData/popularWorkouts.json
> +[{"exercises":[{"exercise":{"title":"Standing Smith Machine Calf Raises","description":"Stand with your feet shoulder-width apart on a raised platform, with the Smith machine bar across your shoulder
Typo in "Leg Worokout". Just CTRL+F you should be able to find it. Maybe even add 1 shorter fullbody workout (30 mins ish) and a longer one (90 mins)

2024-11-25 17:09 UTC, WettyWednesday submitted a review, later dismissed

2024-11-25 17:09 UTC, WettyWednesday commented on src/main/resources/userData/popularWorkouts.json
> +[{"exercises":[{"exercise":{"title":"Standing Smith Machine Calf Raises","description":"Stand with your feet shoulder-width apart on a raised platform, with the Smith machine bar across your shoulder
Typo again. You changed it to "Leg Workkout" lol

2024-11-25 17:10 UTC, WettyWednesday commented on src/main/resources/userData/popularWorkouts.json
> +[{"exercises":[{"exercise":{"title":"Standing Smith Machine Calf Raises","description":"Stand with your feet shoulder-width apart on a raised platform, with the Smith machine bar across your shoulder
You should probably also remove the time in the title since the time is part of the description now

2024-11-26 07:07 UTC, FredBas approved these changes

2024-11-26 07:10 UTC, merged